services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=12345678
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=Hello
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=custom-token
    volumes:
      - ./influxdb/token:/token_storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086"]
      interval: 10s
      timeout: 5s
      retries: 3

  ntp:
    build: ./ntp
    container_name: ntp
    depends_on:
      influxdb:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=Hello
      - INFLUXDB_TOKEN_FILE=/token_storage/token.txt
    volumes:
      - ./influxdb/token:/token_storage
      - shared_excel_data:/shared_volume

  main:
    build:
      context: .
      dockerfile: main/Dockerfile
    container_name: main
    ports:
      - "4001:4001"
    volumes:
      - ./network:/app/main/network
      - shared_excel_data:/shared_volume

  envvarco:
    build:
      context: .
      dockerfile: envvarco/Dockerfile
    container_name: envvarco
    ports:
      - "4002:4002"
    volumes:
      - ./network:/app/envvarco/network
      - shared_excel_data:/shared_volume

  grafana-infinity:
    build: ./grafana-infinity
    container_name: grafana-infinity
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-infinity/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-infinity/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-infinity/dashboards:/var/lib/grafana/dashboards/main

  grafana-influxdb:
    image: grafana/grafana-oss
    container_name: grafana-influxdb
    ports:
      - "3000:3000"
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-influxdb/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-influxdb/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-influxdb/dashboards:/var/lib/grafana/dashboards/main

volumes:
  shared_excel_data:
    name: shared_excel_data