apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: Hello
    editable: true
    isDefault: true