{
 "title": "Node Graph",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 18, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "id", "text": "id", "type": "string" },
      { "selector": "label", "text": "Title", "type": "string" },
      { "selector": "color", "text": "color", "type": "string" },
      { "selector": "base_voltage", "text": "", "type": "string" },
      { "selector": "present_voltage", "text": "Subtitle", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "nodes",
     "source": "url",
     "type": "json",
     "url": "http://host.docker.internal:4000/grafana_data",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "base_voltage", "text": "", "type": "string" },
      { "selector": "id", "text": "id", "type": "string" },
      { "selector": "source", "text": "source", "type": "string" },
      { "selector": "target", "text": "target", "type": "string" },
      { "selector": "thickness", "text": "thickness", "type": "number" },
      { "selector": "Message", "text": "detail_message", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "connections",
     "source": "url",
     "type": "json",
     "url": "http://host.docker.internal:4000/grafana_data",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Node 0",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N0\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N0\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N1\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N2\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N3\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N4\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N4\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 5",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N5\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N5\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 6",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N6\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N6\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 7",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N7\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N7\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 8",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N8\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N8\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 9",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N9\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N9\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 10",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N10\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N10\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 11",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N11\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N11\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 12",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N12\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N12\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 13",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N13\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N13\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node 14",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "from(bucket: \"Hello\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_pu_mag\")\n  |> filter(fn: (r) => r[\"name\"] == \"N14\")\n  |> filter(fn: (r) => r[\"uuid\"] == \"N14\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}